// generated by Fast Light User Interface Designer (fluid) version 1.0303

// TODO get rid of this


#ifndef main_h
#define main_h
#include <FL/Fl.H>
//extern int Guitar_String_Param;
//void bt_callback(Fl_Widget*, void* userdata);
#include <FL/Fl_Double_Window.H>
//extern Fl_Double_Window *window_main;
#include <FL/Fl_Button.H>
#endif
